"""`scan_imzml` against chunks of a real acquisition.

These fixtures are excerpts of an FGCZ export (`S758504_CHCA_20um_bottom`, 59565 spectra,
centroid, zlib-compressed on both binary arrays). They are the only real-world imzML in the
test suite: the differential corpus is generated by this project's own writer, which emits
uncompressed arrays, so its compressed cases are rewritten by hand and inherit that writer's
XML shape.

That matters most for the encoded-length map, which is what lets the imzy backend read
compressed files at all. A map exercised only against files this project wrote would not
prove much about the ones it has to open -- here the compression cvParam sits on a
`referenceableParamGroup` well before the run, and the arrays carry no compression param of
their own, which is exactly the layout the scan has to traverse for.

The values below came from `test_parse_spectra.py`, which pinned them against the
hand-rolled parser's internals. The parser is going away; the values it pinned are not.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from depiction_io.imzy_backend import raise_if_unsupported_compression, scan_imzml


@pytest.fixture
def spectra_path() -> Path:
    return Path(__file__).parent / "chunks" / "spectra_resolve.xml"


def test_detects_zlib(spectra_path: Path) -> None:
    scan = scan_imzml(spectra_path)
    assert scan.unsupported_compression is None
    assert scan.encoded_lengths is not None


def test_zlib_is_read_not_refused(spectra_path: Path) -> None:
    raise_if_unsupported_compression(spectra_path)


def test_encoded_lengths(spectra_path: Path) -> None:
    # Offset -> encoded length for the three spectra in the chunk, m/z array then intensity
    # array. `IMS:1000104` is the compressed size; the element counts (82, 208, 342) live in
    # `IMS:1000103`, which is the only one imzy parses.
    assert scan_imzml(spectra_path).encoded_lengths == {
        16: 667,
        683: 215,
        898: 1598,
        2496: 440,
        2936: 2568,
        5504: 695,
    }


def test_declares_no_z(spectra_path: Path) -> None:
    # The acquisition is 2D: its scans declare position x and y only. imzy reports z = 1
    # regardless, so this is the input to a correction rather than a formality.
    assert not scan_imzml(spectra_path).declares_z
