[project]
name = "depiction_tools"
version = "0.1.0"
description = ""
authors = [{ name = "Leonardo Schwarz", email = "leonardo.schwarz@fgcz.ethz.ch" }]
# TODO
#readme = "README.md"
license = { text = "Apache-2.0" }

dependencies = [
    "depiction_io @ git+https://github.com/fgcz/depiction.git@split-packages#subdirectory=depiction_io",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock",
]

[project.scripts]
depiction-tools = "depiction_tools.cli.cli:app"

[tool.uv]
reinstall-package = ["depiction_tools"]
