site_name: depiction docs
theme:
  name: material
  features:
    - navigation.sections
    - navigation.instant
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            annotations_path: source
            show_category_heading: yes
            show_root_heading: yes
            show_symbol_type_heading: yes
            show_source: no
            members_order: alphabetical
