baseline_adjustment:
  baseline_type: Tophat
  window_size: 3000
  window_unit: ppm
peak_picker:
  peak_picker_type: MSPeakPicker
  fit_type: quadratic
calibration:
  calibration_method: MCC
  model_smoothing_activated: no
n_jobs: 10
requested_artifacts: []
