commands:
  dispatch:
    type: shell
    command: python -m depiction_targeted_preproc.app_interface.dispatch_app
  process:
    type: shell
    command: python -m depiction_targeted_preproc.app_interface.process_chunk
  collect:
    type: shell
    command: python -m depiction_targeted_preproc.app_interface.collect_chunk
