process_spectra:
  steps: []
calibration:
  method:
    calibration_method: ConstantGlobalShift
  n_jobs: 10
n_jobs: 10
# TODO maybe this can be made even more specific for the test, to only include the absolutely required info
requested_artifacts:
  - CALIB_IMAGES
