name: PR Checks
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
  workflow_dispatch:
jobs:
  unit_tests:
    name: PR Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-depiction
        with:
          python-version: 3.11
      - name: Run unit tests
        run: cd tests && python -m unittest discover -s ./unit -p 'test_*.py'
      - name: Code style
        run: ruff check || true
        if: success() || failure()
#code_style:
#  name: Code Style
#  runs-on: ubuntu-latest
#  steps:
#    - uses: actions/checkout@v4
#    - uses: ./.github/actions/setup-depiction
#      with:
#        python-version: 3.11
#    - name: Check code with ruff
#      run:
#        ruff check || true
