name: PR Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ionmapper
        with:
          python-version: 3.11
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install ionmapper
        shell: bash
        run: |
          pip install uv
          uv pip install --system ".[dev,testing]"
      - name: Run unit tests
        run: cd tests && python -m unittest discover -s ./unit -p 'test_*.py'
  code_style:
    name: Code Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-ionmapper
        with:
          python-version: 3.11
      - name: Check code with ruff
        run:
          ruff check || true
